### PR TITLE
Resource optimisations

### PR DESCRIPTION
**Pull request by bluepilledgreat**
Saves 416KB!!! That's almost a half MB!!!
The largest contributor to the file size are font files inside of WPF.UI but I have no idea how to compress font files and have them still work.

### CODE REVIEW

**Comment by RyanLua** [comment]
Have you considered using SVG or WebP? At least for the icons, you can get high resolutions for small file size. And WebP typically has better compression than PNG.

**Comment by bluepilledgreat** [comment]
> Have you considered using SVG or WebP? At least for the icons, you can get high resolutions for small file size. And WebP typically has better compression than PNG.

webp isnt supported in .net 6

**Comment by MrT-tak** [comment]
> > Have you considered using SVG or WebP? At least for the icons, you can get high resolutions for small file size. And WebP typically has better compression than PNG.
> 
> webp isnt supported in .net 6

Sad, you sure a library doesnt exist for webp?
Would love to know!

Thanks for Bloxstrap!

**Comment by bluepilledgreat** [comment]
> Sad, you sure a library doesnt exist for webp? Would love to know!

pretty sure none exist

**Pull request merged**
