### PR TITLE
fix: include unfinished locales in QA builds

### PR DESCRIPTION
**Pull request by nexpid**
If this is intentional — why is it commented out?

### CODE REVIEW

**Review by axellse — CHANGES_REQUESTED** [review]
Locale.cs defines which languages to include, it along with danish is likely commented out due to not being fully translated during last bloxstrap release

**Comment by nexpid** [comment]
> Locale.cs defines which languages to include, it along with danish is likely commented out due to not being fully translated during the last bloxstrap release

Since it'll only be shown in QA builds, I'd say it's okay to uncomment atm?

**Comment by pizzaboxer** [comment]
dude i literally just explained this to you

image

it'll be updated before release

**Comment by pizzaboxer** [comment]
oh wait what

**Pull request merged**
