### PR TITLE
Improve studio support

### PR DESCRIPTION
**Pull request by bluepilledgreat**
Adds the following:
- Studio URI and file handling
- "Launch Roblox Studio" option in launch dialog*
- "Launch Roblox Studio" option in shortcuts*

\* These options are only visible if Roblox Studio is installed.

### CODE REVIEW

**Comment by bruh1555** [comment]
i think this is good lol so hopefully they look at this

**Comment by Pwnz0rserver2009** [comment]
doesn't maximumadhd's roblox studio mod manager essentially already do the exact same thing?

**Comment by CreeperPlays689** [comment]
yooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by MrT-tak** [comment]
I would love for this to get merged. Which version is likely to get added on?

**Comment by MrT-tak** [comment]
> I would love for this to get merged. Which version is likely to get added on?

@bluepilledgreat

**Comment by MrT-tak** [comment]
Yoooo

**Comment by MrT-tak** [comment]
Next update huh

**Pull request merged**
