### PR TITLE
Spelling mistake fix

### PR DESCRIPTION
**Pull request by MarcelDev**

### CODE REVIEW

**Comment by BizzarBlitz** [comment]
pfp checks out

**Comment by MarcelDev** [comment]
> pfp checks out

indeed

**Comment by bluepilledgreat** [comment]
more like a grammar fix

**Review by bluepilledgreat — APPROVED** [review]

**Review by axellse — APPROVED** [review]

**Comment by MarcelDev** [comment]
> more like a grammar fix

I guess

**Review by yesseruser — COMMENTED** [review]
Nice catch! That's something I would probably not notice.

**Pull request merged**
